# Generated by Django 3.0.6 on 2020-05-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
        ('mascota', '0003_auto_20200520_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Persona'),
        ),
    ]
